package inmo.db;

import java.util.Date;

/**
 * Ingreso generated by MyEclipse Persistence Tools
 */

public class Ingreso implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idIngreso;
	private Moneda moneda;
	private Contratos contratos;
	private TipoIngreso tipoIngreso;
	private Liquidaciones liquidaciones;
	private Date fecha;
	private Float monto;

	// Constructors

	/** default constructor */
	public Ingreso() {
	}

	/** minimal constructor */
	public Ingreso(Integer idIngreso) {
		this.idIngreso = idIngreso;
	}

	/** full constructor */
	public Ingreso(Integer idIngreso, Moneda moneda, Contratos contratos,
			TipoIngreso tipoIngreso, Liquidaciones liquidaciones, Date fecha,
			Float monto) {
		this.idIngreso = idIngreso;
		this.moneda = moneda;
		this.contratos = contratos;
		this.tipoIngreso = tipoIngreso;
		this.liquidaciones = liquidaciones;
		this.fecha = fecha;
		this.monto = monto;
	}

	// Property accessors

	public Integer getIdIngreso() {
		return this.idIngreso;
	}

	public void setIdIngreso(Integer idIngreso) {
		this.idIngreso = idIngreso;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public Contratos getContratos() {
		return this.contratos;
	}

	public void setContratos(Contratos contratos) {
		this.contratos = contratos;
	}

	public TipoIngreso getTipoIngreso() {
		return this.tipoIngreso;
	}

	public void setTipoIngreso(TipoIngreso tipoIngreso) {
		this.tipoIngreso = tipoIngreso;
	}

	public Liquidaciones getLiquidaciones() {
		return this.liquidaciones;
	}

	public void setLiquidaciones(Liquidaciones liquidaciones) {
		this.liquidaciones = liquidaciones;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Float getMonto() {
		return this.monto;
	}

	public void setMonto(Float monto) {
		this.monto = monto;
	}

}