package inmo.db;

import java.util.Date;

/**
 * PropiedadesXPropietario generated by MyEclipse Persistence Tools
 */

public class PropiedadesXPropietario implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PropiedadesXPropietarioId id;
	private Propiedades propiedades;
	private Propietario propietario;
	private Date fechaHasta;

	// Constructors

	/** default constructor */
	public PropiedadesXPropietario() {
	}

	/** minimal constructor */
	public PropiedadesXPropietario(PropiedadesXPropietarioId id,
			Propiedades propiedades, Propietario propietario) {
		this.id = id;
		this.propiedades = propiedades;
		this.propietario = propietario;
	}

	/** full constructor */
	public PropiedadesXPropietario(PropiedadesXPropietarioId id,
			Propiedades propiedades, Propietario propietario, Date fechaHasta) {
		this.id = id;
		this.propiedades = propiedades;
		this.propietario = propietario;
		this.fechaHasta = fechaHasta;
	}

	// Property accessors

	public PropiedadesXPropietarioId getId() {
		return this.id;
	}

	public void setId(PropiedadesXPropietarioId id) {
		this.id = id;
	}

	public Propiedades getPropiedades() {
		return this.propiedades;
	}

	public void setPropiedades(Propiedades propiedades) {
		this.propiedades = propiedades;
	}

	public Propietario getPropietario() {
		return this.propietario;
	}

	public void setPropietario(Propietario propietario) {
		this.propietario = propietario;
	}

	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

}