package inmo.db;

/**
 * Quejas generated by MyEclipse Persistence Tools
 */

public class Quejas implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idQuejas;
	private Empleado empleado;
	private Persona persona;
	private Motivo motivo;
	private Contratos contratos;
	private String descripcion;
	private String comentarios;

	// Constructors
	
	/** default constructor */
	public Quejas() {
	}

	/** minimal constructor */
	public Quejas(Integer idQuejas) {
		this.idQuejas = idQuejas;
	}
	public Quejas(Integer idQuejas, Empleado empleado, Persona persona, Motivo motivo, Contratos contratos, String descripcion, String comentarios) {
		super();
		this.idQuejas = idQuejas;
		this.empleado = empleado;
		this.persona = persona;
		this.motivo = motivo;
		this.contratos = contratos;
		this.descripcion = descripcion;
		this.comentarios = comentarios;
	}

	public String getComentarios() {
		return comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}



	public Integer getIdQuejas() {
		return this.idQuejas;
	}

	public void setIdQuejas(Integer idQuejas) {
		this.idQuejas = idQuejas;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Motivo getMotivo() {
		return this.motivo;
	}

	public void setMotivo(Motivo motivo) {
		this.motivo = motivo;
	}

	public Contratos getContratos() {
		return this.contratos;
	}

	public void setContratos(Contratos contratos) {
		this.contratos = contratos;
	}

}