package inmo.db;

/**
 * TituloXEmpleadoId generated by MyEclipse Persistence Tools
 */

public class TituloXEmpleadoId implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Titulo titulo;
	private Empleado empleado;

	// Constructors

	/** default constructor */
	public TituloXEmpleadoId() {
	}

	/** full constructor */
	public TituloXEmpleadoId(Titulo titulo, Empleado empleado) {
		this.titulo = titulo;
		this.empleado = empleado;
	}

	// Property accessors

	public Titulo getTitulo() {
		return this.titulo;
	}

	public void setTitulo(Titulo titulo) {
		this.titulo = titulo;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TituloXEmpleadoId))
			return false;
		TituloXEmpleadoId castOther = (TituloXEmpleadoId) other;

		return ((this.getTitulo() == castOther.getTitulo()) || (this
				.getTitulo() != null
				&& castOther.getTitulo() != null && this.getTitulo().equals(
				castOther.getTitulo())))
				&& ((this.getEmpleado() == castOther.getEmpleado()) || (this
						.getEmpleado() != null
						&& castOther.getEmpleado() != null && this
						.getEmpleado().equals(castOther.getEmpleado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTitulo() == null ? 0 : this.getTitulo().hashCode());
		result = 37 * result
				+ (getEmpleado() == null ? 0 : this.getEmpleado().hashCode());
		return result;
	}

}