package inmo.db;

/**
 * ClausulasXContrato generated by MyEclipse Persistence Tools
 */

public class ClausulasXContrato implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Contratos contratos;
	private Clausulas clausulas;

	// Constructors

	/** default constructor */
	public ClausulasXContrato() {
	}

	/** full constructor */
	public ClausulasXContrato(Contratos contratos, Clausulas clausulas) {
		this.contratos = contratos;
		this.clausulas = clausulas;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Contratos getContratos() {
		return this.contratos;
	}

	public void setContratos(Contratos contratos) {
		this.contratos = contratos;
	}

	public Clausulas getClausulas() {
		return this.clausulas;
	}

	public void setClausulas(Clausulas clausulas) {
		this.clausulas = clausulas;
	}

}